---
- hosts: webserver
  vars:
    - dockerhub_username: "samiraghouri"
    - docker_container_name: "calcy"
    - docker_image_name : "calculator:version1"
  tasks:
    - name: Pull an image
      docker_image:
        name: "{{dockerhub_username}}/{{docker_image_name}}"
        source: pull

    - name: Create docker container with interactive shell
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ dockerhub_username }}/{{ docker_image_name }}"
        state: present
        tty: true
        interactive: true
