---
- hosts: webserver
  vars:
    - docker_container_name: "calcy"
    - docker_image_name : "calculator:version1"
  tasks:
    - name: Pull an image
      docker_image:
        name: "{{dockerhub_username}}/{{docker_image_name}}"
        pull: true

    - name: Start Docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ dockerhub_username }}/{{ docker_image_name }}"
        state: started