---
- hosts: webserver
  vars:
    - dockerhub_username: "samiraghouri"
    - docker_container_name: "calcy"
    - docker_image_name : "calculator:version1"
  tasks:
    - name: Pull an image
      docker_image:
        name: "{{dockerhub_username}}/{{docker_image_name}}"
        source: pull
    - name: Create a docker container
      docker_container:
        name: "{{ docker_container_name }}"
        image: "{{ dockerhub_username }}/{{ docker_image_name }}"
        state: present

    - name: Run container with interactive shell
      docker_container:
        name: "{{docker_container_name}}"
        image: "{{docker_image_name}}"
        command: /bin/bash
        tty: true
        interactive: true